### PR TITLE
Master

### PR DESCRIPTION
**Pull request by amknudtson**

### CODE REVIEW

**Comment by ZeWaPr** [comment]
Very nice work! Good job!

**Comment by ZeWaPr** [comment]
It's gonna take a while for me to merge this because I have to do git stash things to the conflicts. Merge should be in tomorrow or the next day.

**Comment by Visheshk** [comment]
Ah Amanda made these changes without updating her repo first, so there's
going to be some loss of functionality that happens that'll need to be
repaired. But good work, yep!

**Comment by ZeWaPr** [comment]
Oh I see now. Ok. I'm going to "merge" it the dumb way where I sync my repo, add Amanda's changes, and commit.

**Comment by ZeWaPr** [comment]
Ok. I did the sloppy merge. Gonna close this request now.

**Pull request closed without merging**
